version: "3"
services:
  db:
    image: postgres:12.3
    hostname: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sentence_finder_development
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql
      # - .:/data
